### PR TITLE
Update runtime to 3.38

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by BleuBleu** [comment]
Hi!

As you might have seen to the thread on FamiStudio github, I am not the most knowledgeable person about the Linux ecosystem. 

If you could just explain to me what this version correspond to so I can understand a bit better, that would be very appreciated!

-Mat

**Comment by bilelmoussaoui** [comment]
> Hi!
> 
> As you might have seen to the thread on FamiStudio github, I am not the most knowledgeable person about the Linux ecosystem.
> 
> If you could just explain to me what this version correspond to so I can understand a bit better, that would be very appreciated!
> 
> -Mat

There are two things to know about Flatpak. It doesn't use any host stuff to build/run your application. So it needs an SDK which is a set of libraries/tools to build something. Which is used at build time and a runtime which is used to run the application by the user. 

There are three SDK's/runtimes right now. The most basic one Freedesktop and on top of it there's GNOME & KDE ones. The GNOME one for example gets a new release each 6 months (the same time there's a new GNOME). As GNOME/KDE are based on top of Freedesktop, some of the new releases of those, consists of a bump of the "base" runtime/SDK as well.

So this current bump consists of only bumping the minimal required runtime/sdk to build/run the application to a newer release of the GNOME one.

**Comment by bilelmoussaoui** [comment]
It's recommended to update the runtime/sdk unless there's a blocker to that.

**Comment by ernstp** [comment]
Shouldn't flathubbot post a link to a test build?

**Comment by bilelmoussaoui** [comment]
it should but sometimes it fails :) you can type the same thing as below to trigger it again

bot, build

**Review by ernstp — APPROVED** [review]

**Comment by BleuBleu** [comment]
Thanks for the clarification guys. I just tested the build that just came off the build machines and it worked fine (i saw it updated to 3.38). Ill merge it.

-Mat

**Pull request merged**
